phrases = [
  "Check out <a href=\"https://github.com/harrisonhall/slipstream\">slipstream</a>!",
  "1 in 12 people live near an active or potentially active volcano!",
  "Subscribe to my feeds!",
  "> whoami",
]
