# Index page configuration.

phrases = [
  "Check out <a href=\"https://github.com/harrisonhall/slipstream\">slipstream</a>!",
  "1 in 12 people live near an active or potentially active volcano!",
  "Subscribe to my feeds!",
  "> whoami",
]

[[links]]
name = "Links"
url = "/links"

[[links]]
name = "Games"
url = "/games"
target="_blank"

[[links]]
name = "Resume"
url = "/resume"
target="_blank"

