# Article catalogue.
## Article ordering: oldest to newest.

[[articles]]
name = "Launching and Designing hachha.dev"
blurb = "Why this is the way it is."
path = "site_launch_design"
date = "2023-03-20"

[[articles]]
name = "nix, hx, & cdtest"
blurb = "Recent explorations - July 2023"
path = "nix1"
date = "2023-07-07"

[[articles]]
name = "Services, Hobbies, & Productivity"
blurb = "Recent explorations - October 2023"
path = "services1"
date = "2023-10-01"

[[articles]]
name = "2023 Retrospective & 2024 Goals"
blurb = "Dropping out of school, failing the N3, fitness, theming, and optimization"
path = "2023_retro"
date = "2024-04-07"

[[articles]]
name = "A Year on Game Engines"
path = "a_year_on_game_engines"
blurb = "There a many ways to crack an egg."
date = "2024-11-12"

[[articles]]
name = "Slipstream"
path = "slipstream"
blurb = "Fetching and filtering and aggregating, oh my"
date = "2024-11-29"

[[articles]]
name = "Slipknot"
path = "slipknot"
blurb = "Basic CLI slipfeed server utilizing a simple config."
date = "2025-01-29"

# [[articles]]
# name = "Gamertags"
# blurb = "They're pretty neat"
# path = "gamertags"
# date = "2024-06-30"
